apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-fdme
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-fdme@sha256:c677743032a45fc13923a5ef3def259319844690bd07f647863cc51da23ce1c4
        name: my-nodejs
        resources: {}
status: {}
